name: Create new artifact
on: [push]
env: 
  ARTIFACT_NAME: myartifact
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artifact
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
  